server:
  port: 8085

spring:
  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

cloud:
  gateway:
    routes:
      - id: product
        uri: lb://PRODUCT
        predicates:
          - Path=/api/**
      - id: shopping
        uri: lb://SHOPPING
        predicates:
          - Path=/api/**
      - id: user
        uri: lb://USER
        predicates:
          - Path=/users/**
